site_name: Clangen Wiki MkDocs
site_url: https://cgen-tools.github.io/clangen-wiki-mkdocs/
theme:
  name: material
markdown_extensions:
- toc:
    toc_depth: 4
    baselevel: 2
- admonition
- pymdownx.details
- pymdownx.superfences
- admonition
